### ISSUE TITLE
Different possible input formats

### ISSUE THREAD

**Issue by davidsbatista** [davidsbatista/NER-Evaluation#13]
[StanfordNER](https://nlp.stanford.edu/software/crf-faq.html)

- Single-Line
``Switzerland/LOCATION ,/O Davos/PERSON 2018/O :/O Soros/PERSON accuses/O Trump/PERSON of/O wanting/O a/O `/O mafia/O state/O '/O and/O blasts/O social/O media/O ./O``

- CoNNL like
```Switzerland	LOCATION
,	O
Davos	PERSON
2018	O
:	O
Soros	PERSON
accuses	O
Trump	PERSON
of	O
wanting	O
a	O
`	O
mafia	O
state	O
'	O
and	O
blasts	O
social	O
media	O
.	O
```

- xml: TODO (add example)
- inlineXML: TODO (add example)
- tsv: TODO (add example)
- slashTags: TODO (add example)

[spaCy](https://spacy.io/usage/linguistic-features#named-entities)

**Comment by ivyleavedtoadflax** [comment]
@davidsbatista I've merged this into https://github.com/ivyleavedtoadflax/nervaluate/issues/3 so we could close this one for now if you are happy.

**Comment by davidsbatista** [comment]
yes, this was a mistake from my side opening this one this repo.

**Comment by ivyleavedtoadflax** [comment]
Cool, hopefully will make some progress on CONLL in the next few days 👍
