### ISSUE TITLE
Aggregated by entity type results possible error

### ISSUE THREAD

**Issue by iliaschalkidis** [davidsbatista/NER-Evaluation#2]
@davidsbatista first of all, thanx a lot for your great tutorial and your code. I think there is a minor mistake in the computations of the metrics aggregated by entity type:

In line 123-124, you compute the metrics when a predicted entity overlaps with an entity that belongs in different entity type. You count +1 for incorrect for the miss-predicted entity type, which means that this error will affect both actual and possible amounts. In this specific case you have miss-predicted an  instance of entity type A, where there is an instance of entity type B.

In my understanding, it would be more precise to count:
```
evaluation_agg_entities_type[true.type]['strict']['missed'] += 1
evaluation_agg_entities_type[pred.type]['strict']['spurius'] += 1
```

And why is that?

- The miss-predicted instance of entity type A is spurius, given the formal definition 

> "system produces a response (prediction of type A) which doesn’t exit in the golden annotation"

- You also missed an instance of entity type B, given the formal definition 

> "a golden annotation is not captured by a system"

If you do not count  +1 missed items for entity type B in this part of the code, then you won't count it later on in lines 149-150, because you have already appended this entity in list "true_which_overlapped_with_pred".

Maybe I'm wrong, but I feel that these small adjustments improve the notion of precision and recall. I would really like to hear your thoughts. Cheers!

**Comment by davidsbatista** [comment]
Hi @iliaschalkidis, thanks for your insight, indeed you suggestion makes sense to me, according to the definition of `spurius `and `missing`.

When I implemented this code I just followed the description on the [paper](https://www.cs.york.ac.uk/semeval-2013/task9/data/uploads/semeval_2013-task-9_1-evaluation-metrics.pdf), I don't know if the organisers of the challenge ever released an official script to evaluate submissions.

I will update the code accordingly.

**Comment by iliaschalkidis** [comment]
Hi @davidsbatista,

I'm glad you find my comments useful. The problem with the paper is that it does not propose a way to compute metrics per class (entity). Although, your update is different from my proposal:

You added :

```
evaluation_agg_entities_type[pred.e_type]['strict']['missed'] += 1
```

, while i proposed: 

```
evaluation_agg_entities_type[true.e_type]['strict']['missed'] += 1
evaluation_agg_entities_type[pred.e_type]['strict']['spurius'] += 1
```

I propose to update both gold (**true**) _missed_ sum and  **pred**'s _spurius_, both for strict.

Let me know, if we are still in the same page and I get the semantics right 😄

**Comment by davidsbatista** [comment]
we are in the same page, I just did quick and dirty (while leaving from work) and did not look what I did :)

updated accordingly now, thanks again for your interested and suggestion!
