### ISSUE TITLE
Incorrect entities extraction 

### ISSUE THREAD

**Issue by ducalpha** [davidsbatista/NER-Evaluation#3]
If 2 entities of the same types are next to each other, e.g., `tags = ['O', 'B-LOC', 'I-LOC', 'B-LOC', 'I-LOC', 'O']`
Run 
> collect_entities(tags)

Expect: 2 entities.
Actual: `[Entity(type='LOC', start_offset=1, end_offset=4)]`

**Comment by davidsbatista** [comment]
thanks for filling in that BUG, I will try to find the time and correct it, but feel free to also submit and PR and some test example :)

**Comment by davidsbatista** [comment]
it's fixed and I had a test to it, thanks once again for letting me know
