### ISSUE TITLE
Question: Are Partial Matches allowed for Type matching scheme?

### ISSUE THREAD

**Issue by ducalpha** [davidsbatista/NER-Evaluation#4]
Are Partial Matches allowed for Type matching scheme?
On your blog post, precision/recall/f1 section, you wrote "Partial Match (i.e., partial and type)" so I assume it is possible for the Type matching scheme to include some partial match. However, your code seems not count any Partial Matches for the Type matching scheme; and in the drug labeling example, Type has the partial score of 0.

**Comment by kabramova** [comment]
I'd also like to know that. 
In the code the `eval_type = 'partial_matching'` does not seem to be reachable:

```python
for eval_type in ['strict', 'ent_type']:
    [...]
    if eval_type == 'partial_matching':
        precision = (correct + 0.5 * partial) / actual if actual > 0 else 0
        recall = (correct + 0.5 * partial) / possible if possible > 0 else 0
    else:
        precision = correct / actual if actual > 0 else 0
        recall = correct / possible if possible > 0 else 0
    [...]
```

**Comment by davidsbatista** [comment]
Hi, thanks for the feedback :)

So, reading through the SemEval guidelines once cannot understand which evaluation scenarios have `partial counts`, but from the examples in the [reference document ](https://www.cs.york.ac.uk/semeval-2013/task9/data/uploads/semeval_2013-task-9_1-evaluation-metrics.pdf) it seems that `partial counts`can only happen in a `Partial` and `Type` evaluation scenario.

I've updated my code accordingly, also added some tests, feel free to comment it and/or improve it.

Thanks for the feedback,
David
