### ISSUE TITLE
Some problems with evaluation_agg_entities_type

### ISSUE THREAD

**Issue by weichencoder** [davidsbatista/NER-Evaluation#5]
hello, i added two line in your ipynb with two lines:
           'partial':deepcopy(metrics_results),
           'exact':deepcopy(metrics_results),
in this dict:
 results = {'strict': deepcopy(metrics_results),
           'ent_type': deepcopy(metrics_results),
           }
but, at last i found the output of 'possible'/'actual' are both 0.

so i want to ask, why there are no evaluation_agg_entities_type[type]['partial'/'exact']['possible'/'actual'] in compute_metrics func?

**Comment by weichencoder** [comment]
if i don't add two line in your ipynb with two lines:
'partial':deepcopy(metrics_results),
'exact':deepcopy(metrics_results),
in this dict:
results = {'strict': deepcopy(metrics_results),
'ent_type': deepcopy(metrics_results),
}

there would be an error in running the ipynb.

**Comment by weichencoder** [comment]
![2019-02-22 11 17 21](https://user-images.githubusercontent.com/5242184/53244400-bc88bf80-36e5-11e9-8b5c-03e21952cb5f.png)

# there are some errors in the pic.

**Comment by davidsbatista** [comment]
Unfortunately that part is not completely implemented, take a look [here](https://github.com/davidsbatista/NER-Evaluation/blob/master/ner_evaluation/ner_eval.py#L175), it's only implemented globally and not for aggregations by entity type.

I might to do it in the future if I have time, but feel free to open a PR :)

**Comment by ivyleavedtoadflax** [comment]
I have actually been working on this today, I'll open a PR tomorrow, would be great to get some confirmation that it is correct 😀

**Comment by davidsbatista** [comment]
wow! :) thanks once again, I guess the best way is to add some meaningful test cases but, anyway, I can gladly review or code.

**Comment by ivyleavedtoadflax** [comment]
Do you mind if I port the tests over to pytest rather than unittest? It's much easier to debug, and it reduces the amount of infrastructure you need to write around the tests.

**Comment by davidsbatista** [comment]
sure, go ahead.

**Comment by davidsbatista** [comment]
@ivyleavedtoadflax just a quick question, are you working on adding the counts for `possible` and `actual` for the aggregations by entity type? I just ask because your PR was named WIP.

**Comment by ivyleavedtoadflax** [comment]
yes, actually I was literally coding that right now!
