### ISSUE TITLE
True entities considered multiple times

### ISSUE THREAD

**Issue by accuosto** [davidsbatista/NER-Evaluation#6]
Thank you very much for your code and tutorial.

I think that, when looking for overlaps between predicted and true entities, we'd need to make sure that the same true entity hasn't been used before (i.e.: is not in `true_which_overlapped_with_pred`)?
Otherwise there might be spurious entities that match with an already used entity that are not counted.

But, at the same time, it might happen that a "better" match for the same true entity comes after it has already been considered (and possibly, consumed, if we don't allow it to match with multiple predicted entities) - so I think that we'd need to keep track of the type of match for each predicted entity and if a "better" one comes after count the previous one as spurious.

**Comment by davidsbatista** [comment]
What is exactly a better match, can you give some examples?

**Comment by davidsbatista** [comment]
Currently the order of matches is:

1. check if there's an exact match, i.e.: boundary and entity type match
2. check for an exact match but with a different e_type 
3. check for an overlap i.e. not exact boundary match
    3.1 overlaps with the same entity type
    3.2 overlaps with a different entity type
